### ISSUE TITLE
Nodebook cli

### ISSUE THREAD

**Issue by DirtyF** [oncletom/nodebook#163]
Après avoir mis à jour le module `nodebook` en version 0.50, je ne peux toujours pas lancer les exemples tel qu'indiqué en préambule de chapitre.

```
❯ npm install -g nodebook@latest
/usr/local/bin/nodebook -> /usr/local/lib/node_modules/nodebook/bin/cli.js
/usr/local/lib
└── nodebook@0.5.0

❯ nodebook
module.js:472
    throw err;
    ^

Error: Cannot find module 'finalhandler'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodebook/server.js:6:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by oncletom** [comment]
Dès que la 0.5.1 est publiée ça devrait le faire :-) (genre dans 2 minutes)

**Comment by DirtyF** [comment]
👌
